### ISSUE TITLE
Unable to open /dev/mem: Permission denied

### ISSUE THREAD

**Issue by mchamps** [bernardpletikosa/MMM-DHT-Sensor#3]
I'm having issues getting this to work.

```
0|mm       | bcm2835_init: Unable to open /dev/mem: Permission denied
0|mm       | Whoops! There was an uncaught exception...
0|mm       | TypeError: Failed to initialize
0|mm       |     at DHT.read (/home/pi/MagicMirror/modules/MMM-DHT-Sensor/node_modules/rpi-dht-sensor/main.js:7:18)
0|mm       |     at Class.checkTemperature (/home/pi/MagicMirror/modules/MMM-DHT-Sensor/node_helper.js:36:32)
0|mm       |     at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-DHT-Sensor/node_helper.js:29:18)
0|mm       |     at ontimeout (timers.js:365:14)
0|mm       |     at tryOnTimeout (timers.js:237:5)
0|mm       |     at Timer.listOnTimeout (timers.js:207:5)
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by sanjpr** [comment]
did you ever manage to find the solution to this problem?

**Comment by mchamps** [comment]
@sanjpr Still an open issue for me.

**Comment by finn0** [comment]
@mchamps 
Same issue here.
But I'm working under `serveronly` cause my board is Raspi B+, so simply run `sudo node serveronly` and this module works!
Hope there's better solution.
